"""Generate q/tick/sym.q (the tickerplant's schema file) from feed/schema.py.

Run after changing feed/schema.py:
    python scripts/gen_schema.py

KX's tick.q loads ``tick/<src>.q`` at start-up, where <src> is its first
argument (we use the conventional name ``sym``). That file must define one
empty table per data type, with ``time`` and ``sym`` as the first two columns.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from feed.schema import SCHEMAS  # noqa: E402

QTYPE = {"n": "timespan", "p": "timestamp", "s": "symbol", "f": "float",
         "j": "long", "b": "boolean", "d": "date"}


def render() -> str:
    lines = ["/ Table schemas for the kdb+ tickerplant.",
             "/ GENERATED by scripts/gen_schema.py from feed/schema.py -- do not edit by hand.",
             ""]
    for table, cols in SCHEMAS.items():
        body = "; ".join(f"{c}:`{QTYPE[t]}$()" for c, t in cols)
        lines.append(f"{table}:([] {body})")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = ROOT / "q" / "tick" / "sym.q"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render())
    print(f"Wrote {out.relative_to(ROOT)} ({len(SCHEMAS)} tables)")
