/ Table schemas for the kdb+ tickerplant.
/ GENERATED by scripts/gen_schema.py from feed/schema.py -- do not edit by hand.

quote:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); bid:`float$(); bsize:`float$(); ask:`float$(); asize:`float$())
trade:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); price:`float$(); size:`float$(); side:`symbol$(); iv:`float$(); idx:`float$(); tradeid:`long$())
spot:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); price:`float$())
snap:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); mark:`float$(); markiv:`float$(); und:`float$(); idx:`float$(); oi:`float$(); vol:`float$())
ref:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); kind:`symbol$(); expiry:`timestamp$(); strike:`float$(); cp:`symbol$(); csize:`float$(); tick:`float$(); mintrade:`float$(); listed:`timestamp$())
dq:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); minute:`timestamp$(); quotes:`long$(); trades:`long$(); crossed:`long$(); onesided:`long$(); symsupdated:`long$(); latmed:`float$(); latmax:`float$())
gap:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); start:`timestamp$(); end:`timestamp$(); reason:`symbol$())
iv:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); F:`float$(); fsrc:`symbol$(); T:`float$(); bidiv:`float$(); askiv:`float$(); midiv:`float$(); delta:`float$(); gamma:`float$(); vega:`float$(); theta:`float$())
fwd:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); expiry:`timestamp$(); F:`float$(); D:`float$(); seF:`float$(); seD:`float$(); n:`long$(); und:`float$(); undage:`float$(); diff:`float$(); Fused:`float$(); fsrc:`symbol$())
surface:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); expiry:`timestamp$(); T:`float$(); F:`float$(); fsrc:`symbol$(); n:`long$(); a:`float$(); b:`float$(); rho:`float$(); m:`float$(); sigma:`float$(); rmse:`float$(); wrmse:`float$(); inband:`float$(); ming:`float$(); calv:`float$(); afa:`float$(); afb:`float$(); afrho:`float$(); afm:`float$(); afsigma:`float$(); afrmse:`float$(); afinband:`float$(); afming:`float$(); afcal:`float$(); arbgap:`float$(); atmvol:`float$(); rr25:`float$(); bf25:`float$(); cold:`boolean$())
