/ Table schemas for the kdb+ tickerplant.
/ GENERATED by scripts/gen_schema.py from feed/schema.py -- do not edit by hand.

quote:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); bid:`float$(); bsize:`float$(); ask:`float$(); asize:`float$())
trade:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); price:`float$(); size:`float$(); side:`symbol$(); iv:`float$(); idx:`float$(); tradeid:`long$())
spot:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); price:`float$())
snap:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); exch:`timestamp$(); recv:`timestamp$(); mark:`float$(); markiv:`float$(); und:`float$(); idx:`float$(); oi:`float$(); vol:`float$())
ref:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); kind:`symbol$(); expiry:`timestamp$(); strike:`float$(); cp:`symbol$(); csize:`float$(); tick:`float$(); mintrade:`float$(); listed:`timestamp$())
dq:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); minute:`timestamp$(); quotes:`long$(); trades:`long$(); crossed:`long$(); onesided:`long$(); symsupdated:`long$(); latmed:`float$(); latmax:`float$())
gap:([] time:`timespan$(); sym:`symbol$(); asset:`symbol$(); start:`timestamp$(); end:`timestamp$(); reason:`symbol$())
